### PR TITLE
.NET Core

### PR DESCRIPTION
**Pull request by asherber**
Lots of different ways of doing this; I followed a pattern I'm used to from solutions that need to target multiple frameworks. Think of this as a starting point for however you want to do things; you can look at the most recent commit to see what I had to change. The solution compiles, and I verified that I can use the .NET Core assembly to send a transmission.

BTW, I moved all the files under the NetCore project and linked them back to the Framework project because VS doesn't let you do Add As Link in a Core project.

### CODE REVIEW

**Comment by asherber** [comment]
I did get multi-targeting within a single Core assembly working – but then the spec and NUnit assemblies would have to be redone as well, and I didn't want to jump into that just yet. Keeping Core and Fx separate may be the easier way for now.

There are two things I should have done, however:

1. I should have made the conditional compile symbol `NET45` instead of `FRAMEWORK`. The former is defined automatically by the Core compilation process, which will make things easier if this all becomes one assembly at some point.

1.  Since `MailMessageMapping.cs` is only used by the framework project (`MailMessage` doesn't exist in Core), I put the file directly in that project. I should have added it to NetCore, as with all the other files, and used `#if NET45` to surround the entire contents.

**Comment by asherber** [comment]
@darrencauthon I wanted to ping you about your plans for .NET Core. I'm currently starting a project at work that will use SparkPost in a Core environment; I could just use my fork, but it would be nice to have this all part of the actual library. Do you think it's better to wait until VS2017 is released and the tooling and file formats have settled down? Or is this not really on your radar at the moment? I'm happy to help if I can.

**Comment by darrencauthon** [comment]
@asherber Sure, we can chat on Skype or here or whatever.

I'll be honest with you:  The tooling around .Net Core is a huge pain for me.  I don't plan to wait until VS2017, as I'd love to have .Net Core support **today**.  But I can only afford shots of 1, 2, maybe 3 hours of programming at home, and that's not enough for me to release anything right now.

I'm also not sure how I'm to release a .Net Core version on top of the existing codebase.  Is it a separate version?  Do I go 2.0 for .Net core?

**Comment by asherber** [comment]
I'm still finding my way around this stuff myself, and I agree that the tooling is a pain. 

It looks like most libraries have taken the approach of keeping things within a single NuGet package, either just with a Core library or with a Core and a Framework library. This can all be done from a single codebase, either with separate projects referencing the same code files or with a single .Net Standard project that has multitargeting. As I indicated above, separate projects seems to have the advantage of not having to change the testing assemblies; the disadvantage is that you're not directly testing the Core assembly in a Core environment. 

Versioning on the library doesn't necessarily have to jump to 2.0; I've seen other libraries handle this both ways. In this case, the only functionality that is just not available in Core is the stuff to convert from `MailMessage`. If you continued to make a Framework assembly available as well as a Core assembly, I think a bump in minor version would be suffiient under SemVer; if you're going to just a Core assembly and dropping the `MailMessage` stuff, it would need to be 2.0.

**Comment by darrencauthon** [comment]
What you say makes sense.  I think the multi-targeting makes the most sense, but I haven't gotten deeper in it.

I don't want to drop the ```MailMessage``` code if possible.  I think I should be able to switch the parse argument from ```MailMessage``` to dynamic or object, which should be sufficient to keep it working in 4.5 without any complaints from anybody's compiler.  So long as the functionality is preserved, then I wouldn't have to introduce a breaking change and jump a major version. :smile:

**Comment by darrencauthon** [comment]
My schedule has been crazy for about five months, for reasons I won't get into here.  This week I've tried to make sure that I carve out some time for myself, every day.  Monday I played a video game, yesterday I watched a tv show, and perhaps tonight I'll get on github and start programming at home again. :smile:

**Comment by asherber** [comment]
If you want to keep the `MailMessage` stuff, then I do think the best solution is for the NuGet package to contain both a Framework and a Core assembly. Anyone writing for the Framework will get the same assembly they get today, same functionality (no breaking change); anyone targeting Core won't have access to the `MailMessage` things – but they won't have access to the `MailMessage` class either. I would prefer that to just having a Core assembly that includes `MailMessage` via dynamic or object.

The `MailMessage` parsing was just meant as a kind of shim for people with legacy email code; if they're now writing for Core, they're going to rewrite all of that anyway.

In any case, if you want to go the multitargeting route, I think the next step would be to explore what happens with testing. At a glance, it looks like NUnit does support Core, but I'm not sure about SpecFlow. (I see your comment on https://github.com/techtalk/SpecFlow/pull/649#commitcomment-18179299 ) I can start poking at NUnit for the non-spec tests.

**Comment by darrencauthon** [comment]
@asherber 

I'll chew on this idea today.  I know it's meant to be a shim, but it is in the codebase and 1) I don't like introducing breaking changes if it can be avoided, and 2) I feel like letting the shim drive a larger architecture solution is tail-wagging-dog.  

I say that assuming that the multi-targeting solution is the easiest way to maintain a consistent codebase for a library that works against .Net 4.5 and .Net Core.  It seems simpler, and I kinda like this library is "pure" enough for the production library to be consistent across the two with little-to-no-change.  That might be a good line to establish now, with a flow that requires this same level of consistency as we move forward.  

As for testing matters, given the state of .Net Core, I'm ok with keeping the tests going on the 4.5 side -- assuming we can use multi-targeting.

**Comment by darrencauthon** [comment]
@asherber 

I listened to this keynote, and it really got me thinking.... and I agree with him.  Why introduce breaking changes if we don't have to?

https://www.youtube.com/watch?v=oyLBGkS5ICk&list=PLZdCLR02grLofiMKo0bCeLHZC0_2rpqsz

**Comment by asherber** [comment]
I think there may be a misunderstanding here somewhere. (Sorry if some of this is simplistic.) You say you're leaning towards multitargeting as the easiest way to keep a consistent codebase, which I agree with. Multitargeting will automatically produce two different assemblies (Framework and Core), and these can both be packaged in the same NuGet package. Given this setup, I don't see any problem with using conditional compiles to leave `MailMessage` out of the Core assembly, and I don't think that constitutes a breaking change. (And I agree with avoiding breaking changes where possible.) That seems to be a standard way of handling functionality which is present in the Framework but not in Core, and it seems the same to me as a library with async functionality that adds a version to support 4.0 which does not include the async methods. It's not a breaking change because it doesn't break any existing code (which by definition was already targeting 4.5). And it doesn't seem to me like letting the shim drive the architecture, because the architecture decision (multitargeted project, one NuGet package) came first.

Am I misunderstanding your point of view?

In any case, I've merged your latest master changes into my branch, so it's current.

**Comment by asherber** [comment]
Closing this PR and opening a new one with my net_core_new branch, with good ideas from @Gorniv and #136

**Pull request closed without merging**
