### PR TITLE
adding sandbox option

### PR DESCRIPTION
**Pull request by Jetski5822**
defaults to false

### CODE REVIEW

**Comment by Jetski5822** [comment]
Sorry missed a file :/

**Comment by Jetski5822** [comment]
Ignore this

**Comment by darrencauthon** [comment]
@Jetski5822 Why ignore this?  I don't think they had a sandbox when this library was started.  If SparkPost's API wants it, let's get it!  :smile:

**Comment by Jetski5822** [comment]
I did it on the wrong endpoint :) - I got confused (busy day)

**Pull request closed without merging**
