### PR TITLE
Add factory methods for File

### PR DESCRIPTION
**Pull request by asherber**
I've added some `File.Create<T>()` factory methods for more easily creating attachments and inline images from files, byte arrays, and streams.

### CODE REVIEW

**Comment by darrencauthon** [comment]
Thank you!  I'm going to add this to my integration tests, and get it merged with a new version over the holiday weekend.  This makes my Thanksgiving-eve happy! :turkey:  :turkey:

**Comment by asherber** [comment]
I made one small change to remove an unnecessary namespace qualifier on one of the uses of `File`.

**Comment by darrencauthon** [comment]
Thank you!

**Comment by asherber** [comment]
My pleasure – thanks for your work on this library.

**Pull request merged**
