### PR TITLE
add support .net core

### PR DESCRIPTION
**Pull request by Gorniv**
It is work for me.
I didn't upgrade nuget.

### CODE REVIEW

**Comment by darrencauthon** [comment]
Ahh thank you!  I'll take a look soon!

**Comment by asherber** [comment]
I like the organization of this better than my PR – I didn't know about the include syntax in project.json. But I think there are more conditionally compiled bits than needed – some of the syntax that NET Standard requires can also be used by Framework. I'm going to try applying this layout to my branch.

**Comment by asherber** [comment]
Thanks a lot for hacking through this – I've learned a bunch by seeing what you changed, and I'm trying to adapt it for my slightly different solution layout.

I think you're missing the `dotnet build` after `dotnet restore`, though.

**Comment by Gorniv** [comment]
https://travis-ci.org/Gorniv/csharp-sparkpost/jobs/195788065 - work
I want build test for CoreCLR, but test project include many dependencies without support CoreCLR:
AutoMoq - need build .net core(like this)
Unity -  new version in master -  but wihout nuget package(i dont found)
ServiceLocator -  without new version CoreCLR

**Comment by asherber** [comment]
Right, the tests for now can only be run under mono, against the Framework assembly.

**Comment by darrencauthon** [comment]
Thank you guys for your work with this... I've learned a bit reading it, and I'm going to apply that to get AutoMoq upgraded, too!

**Pull request closed without merging**
