### PR TITLE
Mailmessage parsing with cleanup

### PR DESCRIPTION
**Pull request by darrencauthon**
Just some cleanup before morning @asherber 's work.  There's a lot of work to convert a mail message to a transmission, so I thought it would be best if we kept that work in a separate class.

### CODE REVIEW

**Comment by asherber** [comment]
Okay, so apparently we have different styles! I would point out only that having `Parse()` or `LoadFrom()` as a public method was a conscious choice. I was thinking of a use case where I create a `Transmission` and set the Options, Metadata, etc. as I want them, and then sequentially load the content from several different `MailMessages`. IOW:
```csharp
var trans = new Transmission();
trans.Options.etc.;

trans.Parse(message1);
client.Transmissions.Send(trans);

trans.Parse(message2);   // keeping same Options etc.
client.Transmissions.Send(trans);
```

**Comment by asherber** [comment]
You're right that `Parse` wasn't the best name for that method; `LoadFrom` would have been better. And I did see that the method was still available in `MailMessageMapping`, though it's not easily discoverable. (I would suggest some renaming here as well. `ToXxx` methods usually take the object on which they are called and return a different object, but in this case they are operating on the method parameters. I would vote for something like `ConvertToTransmission`, although I'm not crazy about it on the one that also takes a `Transmission` parameter.)

The rest is style. I love me some LINQ as much as the next guy, but to me your code sample is harder to grok at a glance. I'm not sure in this case that I share your concerns about reusing a `Transmission`; I was also envisioning that there might be a lot going on between the first and second sends, so that the `MailMessages` wouldn't be available all at once. But it's not worth fussing about.

**Comment by darrencauthon** [comment]
@asherber I'm ok having the ```LoadFrom``` method back, if you'd like.  I haven't pushed this to nuget yet; I figured we'd let the code settle a bit. :smile:  I'll move it back before I do the final deploy.

**Comment by darrencauthon** [comment]
@asherber When I was reviewing this... I was thinking about replacing the constructor that takes in a MailMessage, and replacing it with a ```Parse``` method that does the same thing.  

My thought is that a transmission is a larger much larger concept than a MailMessage, and putting the MailMessage as an optional constructor argument might elevate the value too much.  Like... this might be a case of too much discoverability?  :smile:

**Comment by darrencauthon** [comment]
Some think I think about the fine details of code a little too hard.... :smile:

**Comment by asherber** [comment]
To me, the constructor makes sense, as passing a collection of constructor arguments, in the same way that the following make sense (a little simplistically):
```csharp
// Option A
public Transmission(string from, string to, string subject, string body) { ... }

// Option B
public class TransmissionParams
{
  public string From { get; set; }
  public string To { get; set; }
  public string Subject { get; set; }
  public string Body { get; set; }
}
public Transmission(TransmissionParams params) { ... }
```
But I wouldn't argue if you wanted to change it.

**Pull request merged**
